Repository teamViNO/Vino-Server, pull requests merged in 2024-02, with the labels that each got.

#89 [fix] 영상알림 선택 읽기 추가 및 검색 api params=> 쿼리형태
  src/controllers/search.controller.js
  src/controllers/user.controller.js
  src/routes/search.route.js
  src/routes/user.route.js
  src/services/user.service.js
Labels: :construction_worker: ci, :clap: feat, :hammer: fix

#90 [fix] 엔드포인트 수정
  src/models/user.dao.js
  src/routes/user.route.js
Labels: :construction_worker: ci, :hammer: fix

#93 [fix].에러 코드 수신
  src/models/video.dao.js
  src/services/video.service.js
Labels: :construction_worker: ci, :hammer: fix

#94 Feature/video
  index.js
  package-lock.json
  package.json
  src/controllers/progress.controller.js
  src/controllers/sms.controller.js
  src/controllers/summary.controller.js
  src/controllers/video.controller.js
  src/routes/translateToMP3.route.js
  src/services/chatGPT.service.js
  src/services/progress.service.js
  src/services/speech.service.js
  src/services/storage.service.js
  src/services/summary.service.js
  src/services/translateToMP3.service.js
Labels: :construction_worker: ci, :clap: feat, :hammer: fix

#95 [fix] type module 제거
  package.json
Labels: :construction_worker: ci, :clap: feat, :hammer: fix

#96 [fix] not find 추가
  src/dtos/video.dto.js
  src/services/video.service.js
Labels: :construction_worker: ci, :hammer: fix

#98 [feat] 카카오 로그인 구현
  index.js
  package-lock.json
  package.json
  src/controllers/kakao.controller.js
  src/models/user.dao.js
  src/routes/kakao.route.js
  src/services/kakao.service.js
Labels: :clap: feat, :hammer: fix

#99 [fix] 영상 상세정보 주기 응답 수정
  package-lock.json
  src/controllers/video.controller.js
  src/dtos/video.dto.js
  src/services/video.service.js
Labels: :construction_worker: ci, :hammer: fix

#100 [fix] 카카오 red uri 수정
  src/routes/kakao.route.js
  src/services/kakao.service.js
Labels: :hammer: fix

#102 [fix] 영상 수정 일부분도 가능하게 변경
  src/dtos/video.dto.js
  src/models/video.dao.js
  src/services/video.service.js
Labels: :construction_worker: ci, :clap: feat, :hammer: fix

#103 [feat] 영상 요약 추가 및 삭제 추가
  src/controllers/video.controller.js
  src/dtos/video.dto.js
  src/models/video.dao.js
  src/models/video.sql.js
  src/routes/video.route.js
  src/services/video.service.js
Labels: :construction_worker: ci, :clap: feat

#104 Feature/video
  package-lock.json
  package.json
  src/models/category.dao.js
  src/services/chatGPT.service.js
  src/services/translateToMP3.service.js
  tempMp3/README.md
Labels: :construction_worker: ci, :hammer: fix

#105 [fix] 닉네임 중복확인 기능 추가
  src/controllers/user.myPage.controller.js
  src/models/user.dao.js
  src/services/user.service.js
Labels: :hammer: fix

#106 [fix] cors 테스트
  index.js
Labels: :hammer: fix

#110 [fix] cors 수정
  index.js
Labels: :hammer: fix

#111 [fix} cors 수정
  index.js
Labels: :hammer: fix

#112 [fix] cors 도메인 추가
  index.js
Labels: :hammer: fix

#113 [feat] sql 추가
  .ebextensions/03_ffmpeg_package.config
  index.js
  src/models/video.sql.js
Labels: :construction_worker: ci, :clap: feat

#114 [fix] 카카오 로그인 redirect_url 수정
  src/services/kakao.service.js
Labels: :hammer: fix

#115 [fix] 카카오 redirect 수정
  src/controllers/kakao.controller.js
  src/services/kakao.service.js
Labels: :hammer: fix

#116 [fix] 카카오 로그인
  src/controllers/kakao.controller.js
Labels: :hammer: fix

#117 [fix] 카카오 로긘
  src/controllers/kakao.controller.js
Labels: :hammer: fix

#118 [fix] 카카오 redirect 수정 및 로그인 시 알림, 카테고리 에러 수정
  src/controllers/kakao.controller.js
  src/services/kakao.service.js
Labels: :hammer: fix

#120 [fix] cors 헤더 허용 추가
  index.js
Labels: :hammer: fix

#122 [fix] 전화번호 인증 재구현
  src/controllers/sms.controller.js
  src/models/sms.dao.js
Labels: :hammer: fix

#129 [fix] 검색 api 수정
  package-lock.json
  src/controllers/search.controller.js
  src/models/search.sql.js
  src/services/search.service.js
Labels: :construction_worker: ci, :hammer: fix

#130 [feat] 더미데이터 주기(전부,안읽음),이미지 링크 수정, 카테고리 id 주는 변경
  src/controllers/video.controller.js
  src/dtos/video.dto.js
  src/models/video.dao.js
  src/models/video.sql.js
  src/routes/video.route.js
  src/services/video.service.js
Labels: :construction_worker: ci, :clap: feat

#131 Feature/video
  src/controllers/progress.controller.js
  src/controllers/summary.controller.js
  src/controllers/video.controller.js
  src/models/video.dao.js
  src/models/video.sql.js
  src/routes/progress.route.js
  src/routes/translateToMP3.route.js
  src/routes/video.route.js
  src/services/chatGPT.service.js
  src/services/progress.service.js
  src/services/speech.service.js
  src/services/summary.service.js
  src/services/video.service.js
Labels: :construction_worker: ci, :clap: feat

#133 [fix] api 엔드포인트 수정
  src/models/category.dao.js
  src/routes/video.route.js
Labels: :construction_worker: ci, :hammer: fix

#135 [feat] 더미 영상 읽기
  src/controllers/video.controller.js
  src/routes/video.route.js
Labels: :construction_worker: ci, :clap: feat

#136 [feat] 영상 모델링 테스트 추가
  package-lock.json
  package.json
  src/controllers/summary.controller.js
  src/services/chatGPT.service.js
Labels: :construction_worker: ci, :clap: feat

#137 [fix] api 수정
  src/controllers/summary.controller.js
  src/services/video.service.js
Labels: :construction_worker: ci, :hammer: fix

#139 [fix] ffmpeg 링크 수정
  .ebextensions/03_ffmpeg_package.config
Labels: :construction_worker: ci, :hammer: fix

#140 [fix] ffmpeg 링크 수정
  .ebextensions/03_ffmpeg_package.config
Labels: :construction_worker: ci, :hammer: fix

#142 [fix] api 수정
  src/services/translateToMP3.service.js
Labels: :construction_worker: ci, :hammer: fix

#143 [fix] api 수정
  Procfile
Labels: :construction_worker: ci, :hammer: fix

#146 [fix] .npmrc 추가
  .github/workflows/dev__deploy.yml
  .npmrc
Labels: :construction_worker: ci, :hammer: fix

#148 [fix] 경로 추가
  src/services/translateToMP3.service.js
Labels: :construction_worker: ci, :hammer: fix

#149 [fix] 경로 추가
  .github/workflows/dev__deploy.yml
Labels: :construction_worker: ci, :hammer: fix

#150 [fix] 경로 추가
  .ebextensions/create_folder.config
Labels: :construction_worker: ci, :hammer: fix

#151 [fix] sql 수정
  src/models/video.sql.js
Labels: :construction_worker: ci, :hammer: fix

#152 [fix] sql 수정
  .ebextensions/permission.config
  src/services/translateToMP3.service.js
Labels: :clap: feat, :hammer: fix

#153 [fix] sql 수정
  package-lock.json
  src/models/video.dao.js
  src/models/video.sql.js
Labels: :construction_worker: ci, :clap: feat

#154 [fix] sql 수정
  src/controllers/summary.controller.js
  src/controllers/video.controller.js
  src/routes/video.route.js
  src/services/chatGPT.service.js
  src/services/video.service.js
Labels: :construction_worker: ci, :hammer: fix

#155 FEAT permmision
  .ebextensions/permission.config
Labels: :construction_worker: ci, :clap: feat

#156 [fix] .ebextensions 추가
  .github/workflows/dev__deploy.yml
Labels: :construction_worker: ci, :hammer: fix

#158 Feature/video
  .github/workflows/dev__deploy.yml
Labels: :construction_worker: ci, :hammer: fix

#160 [fix] 수정
  src/controllers/summary.controller.js
Labels: :construction_worker: ci, :hammer: fix

#161 Feature/video
  src/controllers/summary.controller.js
  src/services/chatGPT.service.js
Labels: :construction_worker: ci, :clap: feat

#162 [feat] 모델링
  src/controllers/summary.controller.js
Labels: :construction_worker: ci, :clap: feat

#168 [FEAT] cookie/token
  index.js
  package-lock.json
  package.json
  src/controllers/summary.controller.js
  src/controllers/user.controller.js
Labels: :construction_worker: ci, :clap: feat

#169 [fix] api 수정
  src/controllers/summary.controller.js
  src/routes/translateToMP3.route.js
Labels: :construction_worker: ci, :hammer: fix

#171 [fix] 내정보 수정 기능(닉네임 설정 오류)
  src/models/user.dao.js
  src/services/user.service.js
Labels: :hammer: fix

#172 [fix] 모델링 nginx 수정
  .platform/nginx/nginx.conf
  src/controllers/summary.controller.js
  src/models/category.dao.js
  src/services/chatGPT.service.js
  src/services/speech.service.js
Labels: :construction_worker: ci, :clap: feat

#173 [feat] 사용자 피드백 기능
  index.js
  src/controllers/feedback.controller.js
  src/models/feedback.dao.js
  src/routes/feedback.route.js
  src/services/feedback.service.js
Labels: :clap: feat

#174 Feature/video
  index.js
  src/controllers/summary.controller.js
Labels: :construction_worker: ci, :clap: feat

#176 fix: await 사용 수정
  src/controllers/category.controller.js
  src/dtos/category.dto.js
  src/models/category.dao.js
  src/services/category.service.js
Labels: :hammer: fix

#182 [fix] 영상 데이터 빈값 수정
  package-lock.json
  package.json
  src/controllers/summary.controller.js
  src/services/video.service.js
Labels: :construction_worker: ci, :hammer: fix

#183 Feature/video
  index.js
  src/controllers/speech.controller.js
  src/controllers/summary.controller.js
  src/controllers/translateMP3.controller.js
  src/routes/translateToMP3.route.js
Labels: :construction_worker: ci, :clap: feat

#186 [feat] 영상 제목
  package-lock.json
  package.json
  src/controllers/summary.controller.js
  src/services/chatGPT.service.js
Labels: :construction_worker: ci, :clap: feat

#187 [fix] 카카오 생일 정보 수정 및 카테고리 자동 생성 파일 이름 변경
  src/services/kakao.service.js
  src/services/user.service.js
Labels: :hammer: fix

#189 [fix] 여러가지 응답 수정
  src/controllers/summary.controller.js
  src/controllers/translateMP3.controller.js
  src/services/video.service.js
Labels: :construction_worker: ci, :clap: feat

#199 [fix] 생년월일 오류 수정
  src/services/kakao.service.js
Labels: :hammer: fix

#201 [fix] 검색 수정
  src/dtos/search.dto.js
  src/models/search.dao.js
  src/models/search.sql.js
  src/services/search.service.js
Labels: :construction_worker: ci, :clap: feat

#202 [fix] 영상변환 알림 수정
  src/controllers/user.controller.js
  src/models/user.dao.js
  src/models/user.sql.js
  src/services/chatGPT.service.js
  src/services/user.service.js
Labels: :construction_worker: ci, :hammer: fix

#204 CORS
  index.js
  src/services/speech.service.js
Labels: :hammer: fix

#206 [feat] video
  src/dtos/video.dto.js
  src/services/video.service.js
Labels: :construction_worker: ci, :clap: feat

#208 [fix] 일부 수정
  .platform/nginx/nginx.conf
Labels: :construction_worker: ci, :clap: feat

#210 Feature/video
  package-lock.json
  package.json
  src/controllers/summary.controller.js
  src/services/chatGPT.service.js
Labels: :construction_worker: ci, :clap: feat

#211 [fix] 1313
  src/models/video.dao.js
Labels: :construction_worker: ci, :hammer: fix

#212 [feat] 태그 api 수정
  src/services/video.service.js
Labels: :construction_worker: ci, :clap: feat

#214 [fix] 전화번호 중복 제한, 임시 비밀번호 12자리로 변경
  src/controllers/sms.controller.js
  src/models/sms.dao.js
  src/services/user.service.js
Labels: :hammer: fix

#215 [fix] 카테고리 삭제 수정
  src/models/category.dao.js
Labels: :construction_worker: ci, :clap: feat

#217 Feature/users
  src/services/video.service.js
Labels: :hammer: fix

#218 [fix] 전화번호 인증 코드 분리
  src/controllers/sms.controller.js
  src/routes/sms.route.js
Labels: :hammer: fix

#219 [feat] video 이름 변경
  src/controllers/summary.controller.js
  src/models/category.dao.js
  src/models/dummyScripts.js
  src/services/video.service.js
Labels: :construction_worker: ci, :clap: feat

#220 [fix] 스왑메모리 설정
  .ebextensions/01_steup_swap.config
  src/services/chatGPT.service.js
  src/services/translateToMP3.service.js
Labels: :construction_worker: ci, :hammer: fix

#221 [fix] 검색 수정
  src/controllers/search.controller.js
  src/services/chatGPT.service.js
Labels: :construction_worker: ci, :clap: feat

#222 [feat]태그검색수정
  src/controllers/search.controller.js
  src/dtos/search.dto.js
Labels: :construction_worker: ci, :clap: feat
